name = "DemoPackageCT"
uuid = "2595073f-793f-4630-9447-6ffb27b69019"
authors = ["Cindy Tu <cindyhfls@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
